name: devsecops pipeline

on:
  workflow_dispatch: 

jobs:
    code-quality-check:
        uses: ./.github/workflows/code_quality.yml

    security-scan:
        uses: ./.github/workflows/secret_scan.yml

    dependency-scan:
        uses: ./.github/workflows/dependency_scan.yml

    docker-lint:
        uses: ./.github/workflows/docker-lint.yml

    docker-build-push:
        needs: [code-quality-check, security-scan, dependency-scan, docker-lint]
        uses: ./.github/workflows/docker-build-push.yml
        secrets: inherit

    trivy_scan:
        needs: [docker-build-push]
        uses: ./.github/workflows/image_scan.yml
        secrets: inherit

    deploy-server:
        needs: [trivy_scan]
        uses: ./.github/workflows/deploy-server.yml
        secrets: inherit