# This workflow is used to lint the Dockerfile using hadolint action
name: Docker lint

on:
    workflow_call:               # Triggered by other workflows

jobs:
    docker-lint:
        runs-on: ubuntu-latest

        steps:
            - name: Check the code
              uses: actions/checkout@v4

            - name: Validate Dockerfile
              uses: hadolint/hadolint-action@v3.1.0
              with:
                dockerfile: Dockerfile
