name: hello

on:
  push:
    branches: [main]

jobs:
  greets:
    runs-on: ubuntu-latest

    steps:
      - name: Say hello to users
        run: echo "Arya Parab"
  details:
    runs-on: ubuntu-latest

    steps:
      - name: use python version
        run: echo "pyhton --version && docker --version"
    
  
