# This workflow is used to scan the code for secrets using Gitleaks action.
#API keys, Passwords, and other sensitive information should not be committed to the repository. This workflow helps to identify such secrets and prevent them from being exposed.
name: secret scan

on:
    workflow_call:               # Triggered by other workflows

jobs:
     secret-scan:
        runs-on: ubuntu-latest

        steps:
            - name: Check the code
              uses: actions/checkout@v4
              with:
                fetch-depth: 0           # Fetch all history for all branches and tags

            - name: Run Gitleaks Scanner
              uses: gitleaks/gitleaks-action@v2
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    #github actions manages this token, no need to create a new one
